### ISSUE TITLE
os error 1332, 5 in Windows 10

### ISSUE THREAD

**Issue by thenasim** [Peltoche/lsd#524] opened 2021-05-29 04:04 UTC
- os: Windows 10 20H2
- `lsd --version`: 0.20.1
- `echo $TERM`: Powershell 5.1
- `echo $LS_COLORS`: 

## Expected behavior
output of ls:

d-----         5/27/2021  10:35 AM                learning
d-----         5/26/2021  11:31 PM                linqpad
d-----        12/20/2020  10:49 PM                mock-server
d-----         2/28/2021  12:08 PM                my-config
d-----          2/7/2021   3:27 PM                my-scripts
d-----         5/10/2021   9:43 PM                projects
d-----         2/10/2021  12:53 PM                rustlings

## Actual behavior
output of lsd:

lsd: .\$RECYCLE.BIN: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\learning: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\mock-server: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\my-config: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\my-scripts: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\projects: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\rustlings: No mapping between account names and security IDs was done. (os error 1332).

lsd: .\System Volume Information: Access is denied. (os error 5).

 linqpad

## Details
Ok, so I have reinstalled my windows 10. After that lsd can not show previous folder that I have in hard drive.

But if I create new folder than lsd can detect and show that file/folder. Here linqpad is the new folder so lsd is showing that without problem.

Also I am getting os error 5 in System Volume Information. Thanks

**Comment by snylonue** [comment] 2021-08-06 04:39
same issue

**Comment by Lunchb0ne** [comment] 2021-08-07 18:19
It happens because of the way Windows does mapping for foreign items, that have been copied over from another NTFS file system, the current implementation uses `lookup_account_sid` but that only does mappings to existing logon sessions on the current device, the issue is being worked on in #473.

**Comment by zwpaper** [comment] 2021-10-07 08:54
closing with https://github.com/Peltoche/lsd/pull/473 merged into master

**Closed by zwpaper** 2021-10-07 08:54 UTC
Labels: os/windows
