### ISSUE TITLE
Problem with Icons in Konsole

### ISSUE THREAD

**Issue by kaefert** [Peltoche/lsd#118] opened 2019-02-07 14:33 UTC
## Expected behavior
The icons should show out of the box on installation and completely. Or the font packages should at least be marked as optional dependency.

## Actual behavior
I've installed lsd on my Manjaro KDE laptop. At first I only got empty boxes instead of icons. After reading a bit I found I could get some icons by installing `ttf-font-awesome` and all of them by installing `ttf-nerd-fonts-symbols`.

Though those icons look cropped in Konsole, and don't show at all in tty (which shows variously sized filled boxes instead).

![screenshot_20190207_152955](https://user-images.githubusercontent.com/1448723/52418129-b099dc80-2aed-11e9-984d-326abd5995f6.png)

I've also talked about this issue in the manjaro forum:
https://forum.manjaro.org/t/replacement-for-ls-lsd-ls-deluxe-icons-problems/74887

And I've aso reported the issue with Konsole here:
https://bugs.kde.org/show_bug.cgi?id=404128

**Comment by Peltoche** [comment] 2019-02-08 22:35
Hi @kaefert ,

Thanks for the report. The way your icons are splitted is weird indeed. Which terminal do you use? Can you try on an other one in order to check if it's an issue with your terminal?

**Comment by kaefert** [comment] 2019-02-09 06:31
Hello @Peltoche !
Yes, it seems to be an issue only in "Konsole" (using version 18.12.1).
I tried "Terminator" (version 1.91.6) which doesn't have this problem.

Though in the tty (non graphical environment) I have another issue with icons:
![img_20190209_071703 jpg_mod](https://user-images.githubusercontent.com/1448723/52517505-90c4fe80-2c3c-11e9-96b2-9ec98571185d.jpg)

**Comment by Peltoche** [comment] 2019-02-09 09:38
Thanks for all the feedbacks! 

For the issue with Konsole I don't know if we can do anything. It seems to be a [bub in Konsole](https://bugs.kde.org/show_bug.cgi?id=272443). For the tty I guess the issue is related to the font used by default. Some configuration with the `setfont` command should do the trick. 

It would be a good idea to document these bugs, I make an issue.

**Comment by kaefert** [comment] 2019-02-09 13:02
thank you for the friendly support!
Could you be a bit more specific about how to employ the `setfont` command? I have no experience with that stuff..

**Comment by Peltoche** [comment] 2019-02-09 13:59
Sorry but I don't have any experience at all in font configuration... I tried some stuff but I didn't succeed.

I just found some useful links:
- [How to install manually a font](https://wiki.archlinux.org/index.php/Fonts#Manual_installation)
- [How to configure a font](https://wiki.archlinux.org/index.php/Font_configuration#Replace_or_set_default_fonts)

I will probably try later but for now I don't have the time for it, sorry. I you found any solution please keep us informed.

**Comment by xircon** [comment] 2019-02-12 10:59
This is a bug in konsole - it also applies to oh-my-zsh/powerlevel9k

https://github.com/bhilburn/powerlevel9k/issues/971

**Comment by annata83** [comment] 2019-03-04 05:35
Same Problem in URxvt-unicode. This are my fonts:
`URxvt.font:xft:TerminessTTFNerdFONTMono:size=12
`

**Comment by emorevival** [comment] 2019-03-04 21:42
I've got the same problem in st as well. Running on Archlabs i3, came out of the box like this


![pic-window-190304-2239-48](https://user-images.githubusercontent.com/32765662/53764788-8a8a1100-3ece-11e9-94f4-a996f7e83b1f.png)

I'm using the mono font

**Comment by finex** [comment] 2019-03-09 00:18
Hi, I've found this, I don't know if it is useful: https://bugs.kde.org/show_bug.cgi?id=390650

**Comment by matthiasbeyer** [comment] 2019-03-11 20:23
I also have problems in xterm:

![2019-03-11-212300_153x47_scrot](https://user-images.githubusercontent.com/427866/54155183-e232fa00-4443-11e9-8983-ee3e672177b2.png)

Not sure whether this is the same bug or something else.

**Comment by emorevival** [comment] 2019-03-11 20:33
my problem was fixed after cloning the [nerd-fonts repo](https://github.com/ryanoasis/nerd-fonts) and running `install.sh`. It's huge, it takes ages, but it solved the problem. May be solvable by patching whatever font lsd uses for its icons but I needed the entire thing for something else anyway.

![pic-window-190311-2129-49](https://user-images.githubusercontent.com/32765662/54155827-3d192100-4445-11e9-9cd9-93b0247c1a61.png)

**Comment by eikeschott** [comment] 2019-03-13 14:02
Have the same issues on Linux Mint 19.1 Cinnamon using Terminator.
**lsd**
![lsd](https://user-images.githubusercontent.com/22131581/54284816-f0e2f380-45a0-11e9-8c64-be3976f4c0fb.png)

**lsd -la**
![lsd_la](https://user-images.githubusercontent.com/22131581/54284824-f6403e00-45a0-11e9-9da0-122859cd68d5.png)

**Comment by DCdeBrabander** [comment] 2019-03-18 22:38
Got same icon issue as @eikeschott (and @matthiasbeyer ?)
![image](https://user-images.githubusercontent.com/2249919/54568213-ad401d80-49d6-11e9-80e5-d01d11f1d99f.png)

I installed the .deb (running Pop OS! which runs Ubuntu 18.10 underneath) 
and I use `lsd` like this:
![image](https://user-images.githubusercontent.com/2249919/54568287-e7a9ba80-49d6-11e9-8689-4b6876bbd5d6.png)

Open for suggestions :-)

**Comment by dummefil** [comment] 2019-03-21 23:18
@DCdeBrabander, @eikeschott please read [https://github.com/Peltoche/lsd/blob/master/README.md#prerequisites](url) and don't make unrelative to issue posts. Thanks.

**Comment by Cory-Watson** [comment] 2019-03-23 20:14
Yakuake also seems to be truncating the lsd icons like Konsole does...

**Comment by BobbyBabes** [comment] 2019-04-16 11:56
I just installed from the Arch Community repo, and the icons show up as boxes.

![lsd-not-displaying-icons_20190416_135446](https://user-images.githubusercontent.com/22870070/56207563-59653a80-604f-11e9-949d-8404d8eecd72.png)

**Comment by Cory-Watson** [comment] 2019-04-16 16:21
@BobbyBabes do you have any of the Awesome fonts installed? I've had better luck with otf-font-awesome (ttf-font-awesome had trouble with whitespace aka %0020, mainly in i3)

**Comment by BobbyBabes** [comment] 2019-04-16 16:34
@Cory-Watson I was laready looking into this one : [https://github.com/gabrielelana/awesome-terminal-fonts](https://github.com/gabrielelana/awesome-terminal-fonts). Found it through the AUR.

**Comment by BobbyBabes** [comment] 2019-04-16 17:12
A little improvement. Yakuake now also displays clipped icons. Also, tried with 2 other Awesome fonts installed from the Arch repo. But exactly the same results, Yakuake and Konsole both display clipped fonts. Thanks for trying to help out.

Now in Yakuake :

![lsd-displaying-clipped-icons-in-yakuake_20190416_190229](https://user-images.githubusercontent.com/22870070/56230007-93e4cc80-607b-11e9-97f0-e5b06515d94d.png)

**Comment by Cory-Watson** [comment] 2019-04-16 17:57
@BobbyBabes, turns out I had aur/awesome-terminal-fonts 1.1.0-2 installed as well.
Konsole and Yakuake both seem to clip off the ends of the lsd icons. 

I'm a big KDE fan, but as for terminals I use terminator more than anything else. It seems to handle the lsd icons fairly well...
![lsd_testing](https://user-images.githubusercontent.com/46908765/56232664-5407f000-604f-11e9-8da7-61d9c8fa5557.png)

**Comment by BobbyBabes** [comment] 2019-04-16 19:39
You're right that's a great file manager, and so was Thunar. I remember those from when I was a CrunchBang and ArchBang user.
I'm going to uninstall the Awesome fonts. Tell you why. Compare the first 2 screenshots that I posted, to the third one. Notice the slightly off triangles at the end of each folder name in the third one ? I have a hunch that that somehow happened because of the Awesome fonts installation (one of the three that I have installed). After that, I'm also uninstalling ```lsd``` because I just found out that it doesn't support the ```--time-style=``` flag of  ```ls```. I usually specify ```long-iso``` or even ```full-iso``` because I need a year in the date.

**Comment by dumbPy** [comment] 2019-04-24 10:37
![Screenshot from 2019-04-24 16-02-41](https://user-images.githubusercontent.com/34011516/56653075-81d1e200-66aa-11e9-89dc-a913ca6a5ea1.png)
This is what it looks on my machine. upper one is suckless-terminal and lower is gnome-terminal
Can't figure out how to fix it. I patched UbuntuMono (after cloning nerd-fonts and using it's install.sh script). That basically messed up my other fonts but the icons are still cropped. Also tried installing awesome-terminal-fonts , didn't help.

font-awesome and powerline nerd-font are not in options in the nerd fonts install script. :disappointed:

**Comment by eclipseo** [comment] 2019-04-25 22:48
It's fixed in Konsole v19.03.80: https://phabricator.kde.org/R319:ed6d8b702fd590d83d3b1db25bf2d1245b1cae33

You can backport this patch if you want https://phabricator.kde.org/file/data/3tu5ac4qtnfxofcrbbmr/PHID-FILE-ut2qllmgagq25jvwdmgn/D18784.diff

**Comment by Zardoz89** [comment] 2019-05-21 15:10
Strange... LSD works out of the box on Kubuntu 18.10 with Firacode font 
![imagen](https://user-images.githubusercontent.com/888483/58107801-e53c2a80-7bea-11e9-8bb5-d016b845b087.png)

I use by default unicode icons as Firacode lacks of some icons that lsd uses, but for me it's ok.

**Comment by Cory-Watson** [comment] 2019-05-21 15:25
@Zardoz89 which terminal are you using?

**Comment by Zardoz89** [comment] 2019-05-21 15:30
Konsole and Yakuake. The capture is Konsole that comes with Kubuntu 18.10

**Comment by romunov** [comment] 2019-06-24 19:13
Fixed after updating Konsole to 19.04.2 (see [here](https://github.com/diogocavilha/fancy-git/issues/39)).

**Comment by Cory-Watson** [comment] 2019-06-24 19:38
Can confirm fixed with Konsole 19.04.2

**Comment by 416207298** [comment] 2020-04-05 03:30
![lsd图标问题](https://user-images.githubusercontent.com/19567041/78466171-b8c0cc80-7730-11ea-8286-f14e205e76d8.jpg)
My icon has show this way, how to fix it?

**Closed** 2020-04-09 09:19 UTC
Labels: bug

**Comment by NamHyeongKeol** [comment] 2021-06-18 09:48
![image](https://user-images.githubusercontent.com/8777446/122542556-caf10700-d065-11eb-9aaa-fb06b573c03c.png)

My icon has show this way, how to fix it?

**Comment by KvizadSaderah** [comment] 2021-07-10 07:45
<img width="549" alt="Screenshot 2021-07-10 at 12 44 21" src="https://user-images.githubusercontent.com/14391797/125155997-a081fd80-e17c-11eb-8b23-28bfb10f4c69.png">
same, if I get it right, it's a font issue? i've got same on debian/ubuntu/mac ¯\_(ツ)_/¯

**Comment by tz4678** [comment] 2021-08-17 00:17
I have same shit after i install kde then delete gnome.

![Screenshot_20210817_031639](https://user-images.githubusercontent.com/12753171/129644557-b3899a51-523c-4d5d-84b8-f6f886604485.png)

**Comment by zwpaper** [comment] 2021-08-17 02:35
Hi @tz4678 , I can't see your problem with your picture posted. this issue is related to a konsole bug https://github.com/Peltoche/lsd/issues/118#issuecomment-462029588 which is fixed https://github.com/Peltoche/lsd/issues/118#issuecomment-505150148, and a font issue https://github.com/Peltoche/lsd/issues/118#issuecomment-462046810, both of them are fixed, I am locking this issue, open a new one and describe your problem if you still have problem with lsd
