### ISSUE TITLE
Failed printing to stdout

### ISSUE THREAD

**Issue by pteroctopus** [Peltoche/lsd#278] opened 2019-09-10 09:14 UTC
lsd -al /usr/bin | head panics at 'failed printing to stdout'.

Screenshot of an error is in attachment with output of standard ls command.

I'm using:
Linux arch 5.2.11-arch1-1-ARCH
zsh 5.7.1 (x86_64-pc-linux-gnu)
lsd 0.16.0

![failed-printing-to-stdout](https://user-images.githubusercontent.com/16186848/64600821-15871f00-d3bc-11e9-9ef2-749bf9149a70.png)

**Comment by Peltoche** [comment] 2019-09-11 16:38
Hi @pteroctopus , thanks for the report.

This is a duplicate of #273 so I close it in order to keep one issue.

**Closed by Peltoche** 2019-09-11 16:38 UTC
Labels: bug

**Comment by Peltoche** [comment] 2019-09-11 16:41
Duplicate of #273
