### ISSUE TITLE
Directory wildcard problem

### ISSUE THREAD

**Issue by jtyr** [Peltoche/lsd#319] opened 2020-01-17 12:32 UTC
`lsd` 0.16.0 is omitting directory names when trying to target a specific file across multiple directories via wildcard:

```shell
mkdir a b c
touch {a,b,c}/test.txt
# Normal ls output
ls */test.txt
a/test.txt  b/test.txt  c/test.txt
# lsd output
lsd --icon never */test.txt
test.txt  test.txt  test.txt
```

**Comment by dvvvvvv** [comment] 2020-02-04 16:11
@Peltoche @meain 
https://github.com/dvvvvvv/lsd/tree/relative-path

I've been working on this issue for a few days. The above branch contains the following modifications:
1. meta::Name includes PathBuf instead of String

2. Name::render function accepts DisplayOption enum value
DisplayOption::FileName: draw file name(using when drawing tree)
DisplayOption::Relative{ base_path }: draw relative path to base_path
DisplayOption::None: draw path it self

3. the file path passed directly has None DisplayOption. so it can draw file paths like ls

$ lsd ../Cargo.*
 ../Cargo.lock   ../Cargo.toml

$ lsd meta/*.rs 
 meta/date.rs        meta/inode.rs   meta/owner.rs         meta/symlink.rs
 meta/filetype.rs    meta/mod.rs     meta/permissions.rs   meta/windows_utils.rs
 meta/indicator.rs   meta/name.rs    meta/size.rs

$ lsd /home/dvvv/src/lsd/src/*.rs
 /home/dvvv/src/lsd/src/app.rs       /home/dvvv/src/lsd/src/flags.rs
 /home/dvvv/src/lsd/src/color.rs     /home/dvvv/src/lsd/src/icon.rs
 /home/dvvv/src/lsd/src/core.rs      /home/dvvv/src/lsd/src/main.rs
 /home/dvvv/src/lsd/src/display.rs   /home/dvvv/src/lsd/src/sort.rs

4. I realized while writing. The relative path option does not seem to be necessary. wow

but This doesn't seem to be rusty code. The Name structure must always have a PathBuf: This is a duplicate of the Meta structure.
I've tried changing it to a Path reference that refers to Meta's PathBuf, but that's not possible because move occurs when the Meta structure is created(as far as I know) .
I've tried changing the Name structure to a Path structure, but that doesn't fit the module named Meta.
I would like to hear you guys opinion.

**Comment by jtyr** [comment] 2020-02-07 14:06
@dvvvvvv Would you mind to create a PR with your change so we can review it?

**Comment by dshahbaz** [comment] 2020-04-10 20:41
hi all, any update on this? this is the only use case where i have to drop back to `/bin/ls`

**Comment by meain** [comment] 2020-09-18 14:36
This should be fixed now.
Feel free to reopen if this issue still persistes.

**Closed by meain** 2020-09-18 14:36 UTC
Labels: bug
