### ISSUE TITLE
snap version gets "Permission denied"

### ISSUE THREAD

**Issue by rubberneck** [Peltoche/lsd#79] opened 2018-12-15 08:25 UTC
This is on ubuntu 18.04.1

## Expected behavior
lsd to give a listing

## Actual behavior
```bash
$ lsd
cannot open directory'.': Permission denied (os error 13)
```

**Comment by Peltoche** [comment] 2018-12-15 12:30
Hi @rubberneck,

Thanks for the report! As each snap run into a specific namespace (or vm I really don't master the subject) it possible that your lsd doesn't have access to your filesystem.

Can you try to reinstall it with the `--classic` option? 
```sh
sudo snap remove lsd
sudo snap instal lsd --classic
```

**Comment by rubberneck** [comment] 2018-12-15 17:47
Yes that works.

**Comment by frankkusel** [comment] 2019-03-04 08:27
Hello.
I have the same problem as the OP, but the problem does not go away with the "--classic" addition to the install command. (I'm using Ubuntu 18.04.2)

**Comment by marxjohnson** [comment] 2019-03-04 09:37
I'm having the same issue on Ubuntu 18.04.  Trying to install with --classic doesn't help:
```
mark@coachz:~$ sudo snap install lsd --classic
Warning: flag --classic ignored for strictly confined snap lsd
```

**Comment by Peltoche** [comment] 2019-03-04 11:07
Hi @frankkusel  and @marxjohnson ,

Thanks for the report!

 I think I made some error in this commit -> https://github.com/Peltoche/lsd/commit/596d20500ea1beefb3049e88d19827af9379b2e2
I move the confinement from `strict` to `classic`. Hoping to be able to remove the `--classic` option but it appear I was wrong... 

I fix that ASAP.

**Comment by wrapperband** [comment] 2019-03-11 10:32
I'm having the same issue with 18.10 and lsd 0.13.0

sudo snap install lsd --classic
Warning: flag --classic ignored for strictly confined snap lsd

and

$ lsd
cannot open directory'.': Permission denied (os error 13)

**Comment by Peltoche** [comment] 2019-03-11 12:36
Hi @wrapperband ,

Thanks for the report, I reopen the issue. 

It's curious because this solution to worked previously. I need to dig a little more into the snap documentation.

**Comment by wrapperband** [comment] 2019-03-11 13:55
I just got it "working" buy installing with --devmode.

If that helps

**Comment by Peltoche** [comment] 2019-03-11 16:27
Hi @wrapperband ,

Thanks for the input but I don't think it's a good practice to install with the devmode because you remove all the jail limitations. On only need a full access to the filesystem but we don't need the access to the network for example.

**Comment by wrapperband** [comment] 2019-03-11 16:39
Cheers, that's why I said "working", in inverted comma's

**Comment by Booteille** [comment] 2019-03-19 19:02
I have the same issue. Can't install snap in classic mode.

**Comment by thexavier666** [comment] 2019-03-21 13:27
Same issue with me. Ubuntu 18.04.

**Comment by MrKaKisen** [comment] 2019-03-24 17:38
I have same issue on Ubuntu 18.04.

**Comment by airfield20** [comment] 2019-04-03 00:41
same issue here ubuntu 18.04

**Comment by krejcar25** [comment] 2019-04-03 07:44
I can confirm it, I am on Ubuntu Server 18.04.2. `--classic` option didn't help, managed to get it installed and working with the `--devmode` as @wrapperband said.

**Comment by Peltoche** [comment] 2019-04-03 13:54
I seriously dont know how to fix this issue... Does someone have some knowledges about the snap permissions system?

**Comment by ralight** [comment] 2019-04-03 14:24
(I'm no snap expert!)

You have the snap set to `strict` confinement, which severely limits what it can access. You probably need to change it to `classic`, and make a request on forum.snapcraft.io for it to be granted classic status, which means it is essentially unconfined.

An example request: https://forum.snapcraft.io/t/request-for-classic-confinement-classic-snap-analyzer/5057

**Comment by ralight** [comment] 2019-04-03 14:27
For debugging this sort of thing more generally, you can use `sudo journalctl --output=short --follow --all | sudo snappy-debug` which will give you suggestions of what might be needed:

```
Log: apparmor="DENIED" operation="open" profile="snap.lsd.lsd" name="/home/user" pid=8988 comm="lsd" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
File: /home/user/ (read)
Suggestion:
* add 'home' to 'plugs
```

You could add `home` to your plugs section as it suggests, but then you still wouldn't have access to non-home files, nor hidden files in the home directory.

**Comment by diddledan** [comment] 2019-04-03 14:30
@ralight that's too much to remember. Simply `snappy-debug.security scanlog` will suffice.

I'm just about to go look at the snapcraft.yaml to see what plugs are applied and will report back.

**Comment by diddledan** [comment] 2019-04-03 14:32
right, so you don't define any plugs, so there are no permissions granted to your snap meaning it can only do things within itself.

```yaml
apps:
  lsd:
    command: bin/lsd
```

You likely need at the minimum `home` to allow users to access files in their home folders:

```yaml
apps:
  lsd:
    command: bin/lsd
    plugs:
      - home
```

You can also allow access to removable disks with `removable-media`:

```yaml
apps:
  lsd:
    command: bin/lsd
    plugs:
      - home
      - removable-media
```

**Comment by kumavis** [comment] 2019-05-21 01:44
tangentially relevant https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci

**Comment by Peltoche** [comment] 2019-05-21 10:01
I will try the "home" and "removeable-media" plug for started but I think there will still have some issues with the `/tmp` folder for example.

**Comment by kakasal** [comment] 2019-05-21 10:53
This is still an unresolved issue.

**Comment by hellerbenjamin** [comment] 2019-05-21 17:09
I had the same issue on linux mint. It runs when installed with --devmode. I have problems with icons, would this be unrelated? 

![image](https://user-images.githubusercontent.com/12040741/58116159-16dfd200-7ba8-11e9-8ef3-b3f2ca42426e.png)

**Comment by brennerm** [comment] 2019-05-22 08:21
@Peltoche When do you plan to release the fix  (#207)?

**Comment by brennerm** [comment] 2019-05-24 12:09
This bug is fixed with version 0.15.0 on my machine.

**Comment by Peltoche** [comment] 2019-05-24 15:38
> This bug is fixed with version 0.15.0 on my machine.

\0/

So I guess the `--classic` is not more needed inside the README?

**Comment by Peltoche** [comment] 2019-05-24 15:39
> After installing with --devmode I have problems with icons, would this be unrelated?

Nop, this is due to a font issue. You need to download a nerd font *and setup your terminal to use it*. Cf the README.

**Comment by brennerm** [comment] 2019-05-24 15:46
That's correct. 👍

**Comment by hellerbenjamin** [comment] 2019-05-25 17:32
OK great thanks for the help with the icons.

**Comment by LeoJhonSong** [comment] 2019-09-04 02:55
![image](https://user-images.githubusercontent.com/37630203/64222275-1d4d4c00-cf02-11e9-9b2e-eb1def3e739e.png)

Hi, althought I am on version 0.16.0 of lsd, on Ubuntu 1804, this issue came up with me :cry: 
I have tried all method mentioned aboved but no one works for me.

Need help!

**Comment by Peltoche** [comment] 2019-09-04 14:10
Hello @LeoJhonSong, 

My guess is that you simply do not have the permissions to read the content of your folder `/etc/ssl/certs` I don't think this is linked to snap. In order to confirm this can you try to run `/bin/ls /etc/ssl/certs`, you should have a similar error. 

If that's the case you will only have to run `sudo lsd` (or `sudo ls`) to see you folder content.

**Comment by LeoJhonSong** [comment] 2019-09-06 12:06
@Peltoche thanks for replying, but as you can see from my screenshot,I have already tried`sudo lsd` and it did not work...

**Comment by Peltoche** [comment] 2019-09-09 12:15
Arf, indeed, my bad... And `/bin/ls` does work or not? Does `lsd` work with some another folder?

**Comment by LeoJhonSong** [comment] 2019-09-09 18:45
Hi, I have tested some more folders, `lsd` woorks with some of them, some not, while `/bin/ls` with all of them, `sudo` is not needed for any folder. Here are my results for `lsd`:

:heavy_check_mark: **/dev**
:x: **/etc**
:heavy_check_mark: **/home**
:heavy_check_mark: **/home/leo**
:x: **/home/leo/snap/gnome-calculator**
:x: **/home/leo/snap/gnome-system-monitor**
:heavy_check_mark: **/lib**
:x: **/media**
:x: **/media/Windows** (this is the mounted partition of my Windows system)
:x: **/mnt**
:x: **/opt**
:heavy_check_mark: **/proc**
:x: **/snap**
:heavy_check_mark: **/tmp**
:x: **/usr**
:heavy_check_mark:  **/usr/bin**
:x: **/usr/share**

This seems quite confussing for me.. I believe there are more folders which `lsd` does not work with and just tell me if you want to check some more folders :+1:

**Comment by Peltoche** [comment] 2019-09-10 09:13
Thanks for the tests. I'm a little lost too. I guess this is related to the snap jail. Can you try to re-install it with the `--classic` flag please? It should give it full access to the file system

**Comment by LeoJhonSong** [comment] 2019-09-11 04:04
@Peltoche Yep I have tried that but unfortunately I got the bug which you have worked on.
![image](https://user-images.githubusercontent.com/37630203/64667199-9f51ed80-d48b-11e9-8276-98dd40e3019a.png)

But with option `--devmode` it works well :man_shrugging:

**Comment by vityafx** [comment] 2019-09-16 06:38
Happened to me on a lot of different machines, have it installed either with `snap` or `apt-get` or `make install`, does not matter. Just now it happened again in just-cloned repository in `/tmp/git-repo`.

**Comment by jsj1027** [comment] 2019-11-13 23:10
Recording here that this issue persists on Pop_OS 19.10(closely based on Ubuntu 19.10)

**Comment by hegonfelipe** [comment] 2019-12-10 18:21
I got the same problem and solved by install tje package with dpkg.

**Comment by Peltoche** [comment] 2019-12-11 09:58
I think I will end up by removing the package from snap and it will solve all the issues.

**Comment by LeoJhonSong** [comment] 2020-03-25 16:34
@Peltoche Hi as I found there is .deb package available, I uninstalled my lsd installed from **snap** and reinstalled lsd with the **.deb package**. And surprisingly lsd works really fine now:tada:

lsd now works fine with every path I mentioned above!

> Hi, I have tested some more folders, `lsd` woorks with some of them, some not, while `/bin/ls` with all of them, `sudo` is not needed for any folder. Here are my results for `lsd`:
> 
>  **/dev**
>  **/etc**
>  **/home**
>  **/home/leo**
>  **/home/leo/snap/gnome-calculator**
>  **/home/leo/snap/gnome-system-monitor**
>  **/lib**
>  **/media**
>  **/media/Windows** (this is the mounted partition of my Windows system)
>  **/mnt**
>  **/opt**
>  **/proc**
>  **/snap**
>  **/tmp**
>  **/usr**
>  **/usr/bin**
>  **/usr/share**
> 
> This seems quite confussing for me.. I believe there are more folders which `lsd` does not work with and just tell me if you want to check some more folders

Congratulation! :tada: I think we could close this issue now.

**Closed** 2020-03-30 08:00 UTC
Labels: bug, help wanted

**Comment by jonas-frey** [comment] 2020-10-03 17:51
I'm using kubuntu 20.20, and the buggy lsd is still available through snap. Can you please remove it? I think that would save a lot of people the trouble of rediscovering the problem and eventually switching to the deb

**Comment by zwpaper** [comment] 2020-10-05 03:48
@Peltoche what's your idea? As we did not support snap anymore, shall we remove it?
I noticed that you are the developer for lsd on snapcraft, could you help to do this?

**Comment by bhechinger** [comment] 2020-11-03 17:06
If this snap is not going to be updated to a version that works properly could you please remove it? It only causes confusion.

**Comment by meain** [comment] 2020-11-05 12:15
From what I could understand, an app once published cannot be removed from the snap store.
https://forum.snapcraft.io/t/how-can-a-developer-remove-her-his-app-from-snap-store/512

**Comment by davidromerot** [comment] 2021-04-07 14:52
I see this same issue (permission denied) when using lsd on Ubuntu 20.04 on Windows (WSL).
I installed lsd, last release, with dpkg.
Just in case, I ran it with sudo (because the errors indicated "permission denied"). It still did not work. It took forever, and threw a few "No such file or directory (os error 2)" errors.

**Comment by notjames** [comment] 2021-08-18 13:31
I just installed this tool last night. It's a great tool, but the greatness of it is moot if you can't list things you should be able to list. How does one install this using dpkg/apt? I don't see it in the base sources. Is there an apt repository one can use so we don't have to worry about using snap?

**Comment by meain** [comment] 2021-08-22 06:15
The snap version has been discontinued and as of now we don't have any plans to update it. If you are using a ubuntu or any other debian derivative refer this section(https://github.com/Peltoche/lsd#on-ubuntu) of the readme on how to install `lsd`.
