### ISSUE TITLE
some symlinks in /usr/bin not seen

### ISSUE THREAD

**Issue by cconverse711** [Peltoche/lsd#306] opened 2019-11-29 05:01 UTC
## Expected behavior
cconverse@converse:~$ ls -l /usr/bin/cc
lrwxrwxrwx 1 root root 20 May 20  2019 /usr/bin/cc -> /etc/alternatives/cc

## Actual behavior
cconverse@converse:~$ lsd -l /usr/bin/cc
cannot access '/usr/bin/cc': No such file or directory (os error 2)

**Comment by Peltoche** [comment] 2019-12-05 10:45
Duplicate of #72

**Closed** 2020-04-09 09:31 UTC
Labels: bug
