### ISSUE TITLE
cannot access '.': Permission denied (os error 13)

### ISSUE THREAD

**Issue by kakasal** [Peltoche/lsd#209] opened 2019-05-21 10:49 UTC
On ubuntu 18 I am getting this error

cannot access '.': Permission denied (os error 13)

**Comment by brennerm** [comment] 2019-05-21 10:53
Getting the same error. Version 0.14.0 installed with snap.

**Comment by Peltoche** [comment] 2019-05-21 11:38
Hi! 

duplicate of #79

**Closed by Peltoche** 2019-05-21 11:38 UTC
Labels: bug
