### ISSUE TITLE
[Feature Request] Implement --ignore-glob

### ISSUE THREAD

**Issue by sumitsahrawat** [Peltoche/lsd#275] opened 2019-09-04 04:46 UTC
I regularly end up using `tree -a -I .git` which shows me a tree of everything including hidden files except the `.git` directories. This doesn't work with `lsd` as `-I/--ignore-glob` isn't supported.

**Comment by Peltoche** [comment] 2019-09-09 15:14
Hi @sumitsahrawat ,

Thanks for the proposal, it seems a good idea indeed. Do you want to give a try and propose an implementation? We would be happy to review it.

**Comment by Pamplemousse** [comment] 2019-10-03 15:52
For the record:
Isn't this a loose duplicate of #263 ?

**Comment by vvuk** [comment] 2019-10-09 20:15
This would be especially useful on Windows, where a user's home dir has some typically hidden files like `NTUSER.DAT{abcdabcd-abcd-abcd-abcd-0123456789}.TMContainer00000000000000000001.regtrans-ms` that completely screw up the ls output

**Comment by vvuk** [comment] 2019-10-09 20:47
@sumitsahrawat tried your commit on top of lsd master, but it doesn't seem to work at all:

```
C:\proj\lsd $ lsd
appveyor.yml  build.rs  Cargo.lock  Cargo.toml  CHANGELOG.md  ci  CODEOWNERS  LICENSE  README.md  src  target
C:\proj\lsd $ lsd -I CODEOWNERS
appveyor.yml  build.rs  Cargo.lock  Cargo.toml  CHANGELOG.md  ci  CODEOWNERS  LICENSE  README.md  src  target
C:\proj\lsd $ lsd --ignore-glob CODEOWNERS*
appveyor.yml  build.rs  Cargo.lock  Cargo.toml  CHANGELOG.md  ci  CODEOWNERS  LICENSE  README.md  src  target
C:\proj\lsd $ lsd --ignore-glob 'CODEOWNERS*'
appveyor.yml  build.rs  Cargo.lock  Cargo.toml  CHANGELOG.md  ci  CODEOWNERS  LICENSE  README.md  src  target
C:\proj\lsd $ lsd --ignore-glob 'C*'
Cargo.lock  Cargo.toml  CODEOWNERS

ci:
before_deploy.bash  before_install.bash  script.bash
```

```

**Comment by sumitsahrawat** [comment] 2019-10-10 01:06
@vvuk This is what I get when directly running from my branch, the branch is already up-to-date on master:

![lsd](https://user-images.githubusercontent.com/5645741/66531058-1086ce00-eb28-11e9-9412-54c3cf34a398.png)

On windows with `cmd`, you might want to try using double quotes to wrap the glob, i.e. something like `"CODEOWNERS*"`.

**Comment by vvuk** [comment] 2019-10-10 01:25
Hm, something's busted on Windows given that `lsd -I CODEOWNERS` doesn't work either.  I'll debug

**Closed** 2019-10-23 08:46 UTC
