### ISSUE TITLE
leading . in hidden file/dir not showed

### ISSUE THREAD

**Issue by mirsella** [Peltoche/lsd#429] opened 2020-10-07 09:54 UTC
when using lsd, even with -a or -A, the leading dot is not showed. I guess it's an intentional design, but I hate it. is there a way to show the leading dot for hidden file / dir with the current version  ? if no, could we add an option to do it ?
thanks

**Comment by meain** [comment] 2020-10-07 10:22
`lsd` even now shows leading dot for hidden files.
Maybe I am not understanding your issue, could you add examples of how it is currently and how you are expecting it to look like.

**Comment by mirsella** [comment] 2020-10-07 10:35
in my case, when using `lsd` in my home dir, all the hidden file and dir appear without the '.' for example .config appear as `(icon) config` if you want a screenshot I can provide one in like 1h30

**Comment by meain** [comment] 2020-10-07 10:50
It does not seem to happen for me. Which OS and version of lsd are you using?

**Comment by mirsella** [comment] 2020-10-07 10:52
so it's a issue.
I'm on manjaro Linux x86_64, I'll send more info about lsd version when I get back to my pc. also is there some sort of log I can upload ?

**Comment by mirsella** [comment] 2020-10-07 11:02
actually the dot are here but are not shown without highlighting it :
![image](https://user-images.githubusercontent.com/45905567/95322812-61491800-089d-11eb-855a-a49c06472413.png)
but only 1 dot at a time. I'll try changing some color scheme

**Comment by meain** [comment] 2020-10-07 11:04
Could you try with `lsd --color never`

**Comment by mirsella** [comment] 2020-10-07 11:05
nop, --color never didn't show the dot. it appear the issue is only with konsole.

**Comment by meain** [comment] 2020-10-07 11:06
How about `lsd --color never --icon never`? If it has dots now, it is probably an issue with the icons in the font.

**Comment by mirsella** [comment] 2020-10-07 11:07
yep work with --icon never. i'm using source code pro variable pro 12, I'll trychanging it

**Comment by mirsella** [comment] 2020-10-07 11:10
switched to source code nerd pro and it work but I really don't like the font. what are you using ?

**Comment by meain** [comment] 2020-10-07 11:13
Closing the issue. The problem is with either the font or how Konsole renders it.
I don't personally use icons a lot, but you can find a lot of fonts here which should work well. https://www.nerdfonts.com/font-downloads

**Closed by meain** 2020-10-07 11:13 UTC
Labels: kind/bug

**Comment by meain** [comment] 2020-10-07 11:18
@mirsella This probably is an issue only with variable fonts. Don't think terminal are good with them. Just my hunch. Try a non variable version of `source code pro` if available and that should work.

**Comment by mirsella** [comment] 2020-10-07 12:08
yep switched to source code pro nerd font, it was in the AUR
