### ISSUE TITLE
Ignore option

### ISSUE THREAD

**Issue by sandorex** [Peltoche/lsd#184] opened 2019-04-10 16:55 UTC
Add the `--ignore` option like on `ls`

**Comment by meain** [comment] 2019-04-11 07:14
Great idea, maybe we could even have another flag which will automatically parse `.gitignore` file and ignore the files listed in there.

If anyone would like to take this up and need some help, feel free to ping me and I could help you out with it.

**Comment by Peltoche** [comment] 2019-10-29 13:14
Duplicate of #275

**Closed by Peltoche** 2019-10-29 13:14 UTC
Labels: enhancement
