### ISSUE TITLE
Feature: Option to exclude files

### ISSUE THREAD

**Issue by alichtman** [Peltoche/lsd#263] opened 2019-08-08 05:09 UTC
It would be great if I could exclude certain files from my `ls` output, like `.DS_Store`. I'm thinking there should be a `lsd --exclude` option, which can be used like this for one or more arguments?

```bash
$ lsd --exclude .DS_Store`
$ lsd --exclude [.DS_Store, .other_files, ...]
```

There's probably a better solution, but this is all I've got off the top of my head.

**Comment by mariksolo** [comment] 2019-08-11 03:54
I'll start working on it.

**Comment by zfogg** [comment] 2019-09-28 16:20
+1 :)

**Comment by Peltoche** [comment] 2019-10-11 13:11
Hello everyone, I close this issue because it's kind of a duplicate of #275 which is more active. If you want to comment or contribute I invite you to do it on the other issue.

**Closed by Peltoche** 2019-10-11 13:11 UTC
