### ISSUE TITLE
ZSH problems tabcompleting directories and files after using DATE= modifier

### ISSUE THREAD

**Issue by arkinzoodsma** [Peltoche/lsd#481] opened 2021-02-04 15:24 UTC
- os: Linux 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 GNU/Linux
- `lsd --version`: lsd 0.19.0 (built from master)
- `echo $TERM`: xterm-kitty & xterm-256color alacritty
- `echo $LS_COLORS`: -

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.

After adding the --date= modifier like and pressing tab in zsh it should tab complete:

lsd --date=relative  \<tab> etc.
lsd --date relative  \<tab> etc.
lsd --date='relative'  \<tab> etc.
lsd --date="relative" \<tab> etc.

# Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.

After adding the --date= modifier like:

lsd --date=relative  \<tab> 
lsd --date relative  \<tab>
lsd --date='relative'  \<tab>
lsd --date="relative" \<tab>

it shows:
Completing option
--all             -a  -- Do not ignore entries starting with .
--almost-all      -A  -- Do not list implied . and ..
--blocks              -- Specify the blocks that will be displayed and in what order
--classic             -- Enable classic mode (no colors or icons)
etc.

**Comment by meain** [comment] 2021-02-05 04:33
Duplicate of https://github.com/Peltoche/lsd/issues/385

**Closed by meain** 2021-02-05 04:33 UTC
