### ISSUE TITLE
Can custom color theme for date supports more date?

### ISSUE THREAD

**Issue by FischLu** [Peltoche/lsd#640] opened 2022-03-20 12:46 UTC
First of all, I really love this feature, which can help me easily to distinguish the files which are modified recently. Current, I see the color theme for data supports 3 different data, `hour-old`, `day-old`, `older`. Does it support more data like 5 minutes old, 2 hours old etc. Thank you!

**Comment by meain** [comment] 2022-03-21 07:43
Duplicate of https://github.com/Peltoche/lsd/issues/359

**Closed by meain** 2022-03-21 07:43 UTC
Labels: duplicate
