### ISSUE TITLE
--long + --group displays GID in multiuser environments, not group names

### ISSUE THREAD

**Issue by sklages** [Peltoche/lsd#398] opened 2020-08-09 18:34 UTC
When using the long listing format (--long or -l) with the --group or -g option, the group identifiers displayed are the numeric GIDs, not the group names for most groups. The user names display as expected.
`exa` has the same problem (not fixed).

Is this something that is on the dev roadmap?

**Comment by zwpaper** [comment] 2020-09-21 10:34
man for ls:

```
-g     like -l, but do not list owner
```

example output:

```shell
[root@localhost /]# ls -l -g
total 28
lrwxrwxrwx.   1 root    7 Aug  3 20:28 bin -> usr/bin
dr-xr-xr-x.   5 root 4096 Aug  3 20:52 boot
drwxr-xr-x.   4 root   70 Aug 31 17:19 data
drwxr-xr-x.  19 root 3920 Sep  8 20:09 dev
drwxr-xr-x.  90 root 8192 Sep 21 10:25 etc
drwxr-xr-x.  11 root 4096 Sep 18 18:37 home
```

looks like that this is working as expected?

**Comment by sklages** [comment] 2020-09-22 16:30
hmm, I am afraid, I don't get it.

When I run `lsd -l` I see the correct group name for my files/folders. 

Other users group names are displayed as group id only (GID), e.g. `1234` instead of `prjgrp`.

This is true for most, but not all files/groups.

E.g. `root`. Here the group is correctly displayed as `root`.

**Comment by sklages** [comment] 2020-09-22 16:34
Maybe https://github.com/ogham/rust-users/issues/40

**Comment by zwpaper** [comment] 2020-09-23 09:10
can you provide some examples? and the output of `ls -l`

I have tried `lsd -l` for 2 users, and it work as expected, the group name is shown:

```
[vagrant@arch home]$ lsd -l
drwx------ tester  tester  4 KB Wed Sep 23 09:08:04 2020  tester
drwx------ vagrant vagrant 4 KB Sun Sep 20 07:57:02 2020  vagrant
```

**Comment by sklages** [comment] 2020-09-25 10:35
```
drwx------ user_a   8000     2020-06-22 01:02:07   26 B   user_a
drwxrwxr-x user_b   1993     2016-09-20 13:44:24   10 B   user_b
drwxr-xr-x user_c   8405     2017-07-28 14:47:33   38 B   user_c
drwxr-xr-x user_d   8382     2017-07-21 10:36:31   32 B   user_d
drwxrwx--- user_e   user_e   2020-05-12 15:59:57    4 KB  user_e
drwxrws--- user_a   16023    2019-04-15 16:21:37  100 B   CancerGenomics
lrwxrwxrwx root     root     2020-01-13 09:16:27   21 B   abc ⇒ /project/abc-cluster
lrwxrwxrwx root     root     2018-07-27 11:03:11   22 B   def ⇒ /project/def-cluster
drwxrwx--x user_f   5252     2017-11-28 12:51:36  101 B   david
```

all these numbers in group column should be displayed as group name, just like `ls -l` correctly does.
It does not make any difference wether these files are local or via NFS(4) ...

**Comment by zwpaper** [comment] 2020-09-25 10:41
Could you provide more info like:
- which Linux Distro, maybe `cat /etc/os-release`
- `lsd-musl` or `lsd-gnu`, how do you installed lsd

maybe related to https://github.com/Peltoche/lsd/issues/374

**Comment by zwpaper** [comment] 2020-09-25 10:46
After diving into the PR you provided, I may find the cause, I will look at it this weekend.

**Comment by sklages** [comment] 2020-09-25 10:58
No MUSL, standard build with `cargo install --git https://github.com/Peltoche/lsd.git --branch master`. 
Not an issue on my local machine, as there is only me, myself and I (ok, and root)  ;-)
My workhorses for working are in-house developed linux systems, 64bit.

**Comment by zwpaper** [comment] 2020-10-04 15:10
hi @sklages , I noticed that you are using cargo to install lsd, can you try my patch so that we can confirm if the bug is blocked by https://github.com/ogham/rust-users/pull/38

```shell
cargo install --git https://github.com/zwpaper/lsd.git --branch fix-group-name-in-gid
```

**Comment by sklages** [comment] 2020-10-06 09:44
Works like a charm AFAICS ... :+1:

**Comment by sklages** [comment] 2020-10-06 09:44
Works like a charm AFAICS ... :+1:

**Comment by zwpaper** [comment] 2020-10-07 09:41
We will fix this as soon as https://github.com/ogham/rust-users/pull/38 merged

**Closed** 2020-10-17 04:05 UTC
Labels: kind/bug, os/linux, status/in-progress
