### ISSUE TITLE
Feature Request: non-human readable format

### ISSUE THREAD

**Issue by ryanmjacobs** [Peltoche/lsd#206] opened 2019-05-21 06:58 UTC
Is there any way to run a standard `ls -l`?

For example,
```console
$ ls -l
-rwxr--r--  1 ryan users 4655644672 May 20 16:34  [redacted]
drwxr-xr-x  8 ryan users       4096 May  7 22:44  [redacted]
drwxr-xr-x  6 ryan users       4096 May 16 15:43  [redacted]
...
```

**Comment by d10xa** [comment] 2019-05-21 10:51
```
/bin/ls -l
```

**Comment by ryanmjacobs** [comment] 2019-05-21 10:57
@d10xa :sweat_smile: I understand that `/bin/ls -l` achieves the aftermentioned effect...

But then I would lose all the extra coloring and formatting of `lsd`. I would love to completely replace `ls` with `lsd`. My only gripe is that single `ls -l`  interop.

Maybe if we introduce a simple long-option (`--no-default-human-readable`), that could fix it? I don't want to introduce an odd single-letter flag as that would be cumbersome. I'm willing to write the code. I just want to verify that this okay / would be acceptable to merge.

**Comment by Peltoche** [comment] 2019-05-21 12:22
Hi! 
This is a duplicate of #211 . In order to keep the discussions centralized I close this issue.

**Closed by Peltoche** 2019-05-21 12:22 UTC
Labels: duplicate
