### ISSUE TITLE
windows os error 5

### ISSUE THREAD

**Issue by bigdogs** [Peltoche/lsd#666] opened 2022-06-07 05:14 UTC
![image](https://user-images.githubusercontent.com/20614926/172301030-5e89d2c2-5722-4723-9628-86a3436fe35b.png)

**Comment by bigdogs** [comment] 2022-06-07 06:37
Not sure if this is related to "C:/System Volume Information", I delete this folder today as it takes too much space

**Comment by zwpaper** [comment] 2022-06-08 08:55
seems like some permission problems, did you try the newest version of lsd?

**Comment by bigdogs** [comment] 2022-06-08 09:04
> seems like some permission problems, did you try the newest version of lsd?

Yes,  It's the latest version  `lsd 0.21.0` . 
Perhaps it was because some security settings are applied by my company administrator :(

**Comment by bigdogs** [comment] 2022-06-16 03:24
After upgrade lsd to `0.22.0`,  the error becomes `os error 1355`
![image](https://user-images.githubusercontent.com/20614926/173984346-e235c59d-04eb-45f9-bc75-e841f6168032.png)

**Comment by meain** [comment] 2022-06-16 05:49
Duplicate of https://github.com/Peltoche/lsd/issues/386 and https://github.com/Peltoche/lsd/issues/334
Closing as of now so that we can continue tracking in those issues.

**Closed by meain** 2022-06-16 05:49 UTC
Labels: help wanted, os/windows
