### ISSUE TITLE
Windows 11 OS Error 1355

### ISSUE THREAD

**Issue by Spacelord-XaN** [Peltoche/lsd#656] opened 2022-05-11 06:30 UTC
- os: Windows 11 21H2
- `lsd --version`: lsd 0.21.0
- `echo $TERM`: cmd.exe
- `echo $LS_COLORS`:  Environment variable LS_COLORS not defined

Run lsd.exe without any arguments in a Windows command prompt.

## Expected behavior
Files and directories are listed.

## Actual behavior
`lsd: .: The specified domain either does not exist or could not be contacted. (os error 1355).`

**Comment by Spacelord-XaN** [comment] 2022-05-12 06:29
I just made a test on another machine that runs the same windows 11 version and there lsd works fine.
Maybe the error has something to do with upgrading from windows 10. As the machine where I get the above error was upgraded from windows 10 to 11 where the other machine is a new installation of windows 11.

**Comment by meain** [comment] 2022-05-12 11:02
Duplicate of https://github.com/Peltoche/lsd/issues/334 . Closing.

**Closed by meain** 2022-05-12 11:02 UTC
